branchName: ${issue.title}
gitSafeReplacementChar: '-'
branches:
    - label: bug
      prefix: bug/${assignee.login}/
    - label: enhancement
      prefix: feat/${assignee.login}/
    - label: '*'
      prefix: ${assignee.login}/
