version: '3.8'
services:
    bot:
        container_name: bot
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        restart: unless-stopped
        links:
            - mongo
            - nginx
    mongo:
        container_name: mongo
        image: mongodb/mongodb-community-server
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    nginx:
        container_name: nginx
        image: nginxproxy/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
