version: '3.8'
services:
    bot:
        container_name: bot
        image: job-offer-bot-bot
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=bot.guidoporcaro.dev
            - LETSENCRYPT_HOST=bot.guidoporcaro.dev
            - VIRTUAL_PORT=80
        expose:
            - "80"
        depends_on:
            - mongo
            - nginx
    mongo:
        container_name: mongo
        image: mongo:7.0
        volumes:
            - ./bot-data/mongo:/data/db
        expose:
            - "27017"
        healthcheck:
              test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
              interval: 10s
              timeout: 5s
              retries: 3
              start_period: 5s
        restart: unless-stopped
    nginx:
        container_name: nginx
        image: nginxproxy/nginx-proxy:1.3.1
        environment:
            - TZ=Europe/Rome
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./bot-data/nginx/certs:/etc/nginx/certs:ro
            - ./bot-data/nginx/vhost.d:/etc/nginx/vhost.d
            - ./bot-data/nginx/html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: unless-stopped
    acme-companion:
        image: nginxproxy/acme-companion:2.2.8
        container_name: nginx-proxy-acme
        environment:
            - TZ=Europe/Rome
            - DEFAULT_EMAIL=support@guidoporcaro.dev
            - NGINX_PROXY_CONTAINER=nginx
        volumes:
            - ./bot-data/nginx/certs:/etc/nginx/certs:rw
            - ./bot-data/nginx/vhost.d:/etc/nginx/vhost.d
            - ./bot-data/nginx/html:/usr/share/nginx/html
            - ./bot-data/nginx/acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
